version: '3.6'
services:
  postgres:
    image: "postgres:latest"
    restart: always
    networks:
      - private
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: POSTGRESPASS
      POSTGRES_DB: awx

  rabbitmq:
    image: "rabbitmq:latest"
    restart: always
    networks:
      - private
    environment:
      RABBITMQ_DEFAULT_VHOST: awx
      RABBITMQ_DEFAULT_USER: awx
      RABBITMQ_DEFAULT_PASSWORD: RABBITPASS

  memcached:
    image: "memcached:latest"
    restart: always
    networks:
      - private

  awx_web:
    # image: "geerlingguy/awx_web:latest"
    image: "ansible/awx_web:latest"
    restart: always
    networks:
      - private
    links:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - "8080:8052"
    hostname: awxweb
    user: root
    environment:
      SECRET_KEY: SECRETKEY
      DATABASE_USER: awx
      DATABASE_PASSWORD: POSTGRESPASS
      DATABASE_NAME: awx
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: awx
      RABBITMQ_PASSWORD: RABBITPASS
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      VIRTUAL_HOST: DOMAIN
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: DOMAIN
      LETSENCRYPT_EMAIL: CONTACT

  awx_task:
    # image: "geerlingguy/awx_task:latest"
    image: "ansible/awx_task:latest"
    restart: always
    networks:
      - public
      - private
    links:
      - rabbitmq
      - memcached
      - awx_web:awxweb
      - postgres
    hostname: awx
    user: root
    environment:
      SECRET_KEY: SECRETKEY
      DATABASE_USER: awx
      DATABASE_PASSWORD: POSTGRESPASS
      DATABASE_NAME: awx
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: awx
      RABBITMQ_PASSWORD: RABBITPASS
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    networks:
      - public
      - private
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
      - /apps/docker-articles/nginx/certs:/etc/nginx/certs:ro
      - /apps/docker-articles/nginx/html:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.5
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
      - /apps/docker-articles/nginx/certs:/etc/nginx/certs:rw
      - /apps/docker-articles/nginx/html:/usr/share/nginx/html

networks:
  private:
    driver: bridge
    internal: true
  public:
    driver: bridge
